### ISSUE TITLE
CommerceML\Nodes\Document комментарии к заказу

### ISSUE THREAD

**Issue by mavsan** [arsengoian/commerce-ml#3]
Пытаюсь скрестить модуль и 1C-Битрикс, добавил тэг <Контейнер> (пока не делал PR, тестирую). Нашел вот что: в `CommerceML\Nodes\Document::getChildFields()` нельзя добавить комментарии, это так и должно быть, или "остатки" от чего-то?

**Comment by arsengoian** [comment]
Полагаю, что остатки. Спасибо за вклад!!

**Comment by mavsan** [comment]
НЗ :) полезная-же вещь и нужная, правки внесены в #4
